'use client';
import { useState, type FormEvent, type ReactNode } from 'react';
import { applyDamage, applyFinancialItemToPayroll, approveDamage, approveFinancialItem, approveObjection, cancelFinancialItem, closeDamage, closeObjection, createDamageObjection, createEmployeeDamage, createEmployeeFinancialItem, markFinancialItemPaid, rejectDamage, rejectFinancialItem, rejectObjection, reviewObjection, settleFinancialItem, submitDamage, submitFinancialItemForApproval, updateEmployeeFinancialItem } from '../../../../lib/employee-financial-actions';

type Access = { canViewAmounts: boolean; canManageFinancial: boolean; canApproveFinancial: boolean; canManageDamage: boolean; canCreateObjection: boolean; canReviewObjection: boolean; canFinance: boolean; canExport: boolean };
type FinancialItem = { id: string; title: string; amount: string; type: string; status: string; description: string | null; effectiveDate: string; paymentAmount: string | null };
type Objection = { id: string; description: string; documents: string | null; status: string; createdAt: string };
type Damage = { id: string; title: string; description: string; amount: string; status: string; incidentDate: string; effectiveDate: string; documentReference: string | null; objections: Objection[] };
type Audit = { id: string; action: string; oldStatus: string | null; newStatus: string | null; actor: string; createdAt: string };
type Action = (formData: FormData) => Promise<unknown>;

const money = (value: string) => `${new Intl.NumberFormat('fa-IR').format(Number(value))} ریال`;
const date = (value: string) => new Intl.DateTimeFormat('fa-IR', { dateStyle: 'medium', timeStyle: value.includes('T') ? 'short' : undefined }).format(new Date(value));
const statusLabel: Record<string, string> = { DRAFT: 'پیش‌نویس', PENDING_APPROVAL: 'در انتظار تأیید', APPROVED: 'تأیید شده', APPLIED_TO_PAYROLL: 'اعمال در حقوق', PAID: 'پرداخت شده', SETTLED: 'تسویه شده', REJECTED: 'رد شده', CANCELLED: 'لغو شده', PENDING_REVIEW: 'در انتظار بررسی', APPLIED: 'اعمال شده', CLOSED: 'بسته شده', SUBMITTED: 'ثبت شده', UNDER_REVIEW: 'در حال بررسی' };
const actionLabel: Record<string, string> = { CREATE_FINANCIAL_ITEM: 'ایجاد آیتم', UPDATE_FINANCIAL_ITEM: 'ویرایش آیتم', SUBMIT_FINANCIAL_ITEM: 'ارسال تأیید', APPROVE_FINANCIAL_ITEM: 'تأیید', REJECT_FINANCIAL_ITEM: 'رد', APPLY_PAYROLL: 'اعمال در حقوق', MARK_PAID: 'ثبت پرداخت', SETTLE: 'تسویه', CANCEL_FINANCIAL_ITEM: 'لغو', CREATE_DAMAGE: 'ایجاد خسارت', SUBMIT_DAMAGE: 'ارسال خسارت', APPROVE_DAMAGE: 'تأیید خسارت', REJECT_DAMAGE: 'رد خسارت', APPLY_DAMAGE: 'اعمال خسارت', CLOSE_DAMAGE: 'بستن خسارت', CREATE_OBJECTION: 'ثبت اعتراض', REVIEW_OBJECTION: 'بررسی اعتراض', APPROVE_OBJECTION: 'تأیید اعتراض', REJECT_OBJECTION: 'رد اعتراض', CLOSE_OBJECTION: 'بستن اعتراض', EXPORT_COMPENSATION: 'خروجی CSV' };

function ActionForm({ action, confirmText, success, children, className }: { action: Action; confirmText: string; success: string; children: ReactNode; className?: string }) {
  const [pending, setPending] = useState(false); const [message, setMessage] = useState<{ type: 'error' | 'success'; text: string } | null>(null);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (pending || !window.confirm(confirmText)) return; setPending(true); setMessage(null); try { await action(new FormData(event.currentTarget)); setMessage({ type: 'success', text: success }); } catch (cause) { setMessage({ type: 'error', text: cause instanceof Error ? cause.message : 'عملیات انجام نشد؛ دوباره تلاش کنید.' }); } finally { setPending(false); } }
  return <form className={className} onSubmit={submit} aria-busy={pending}>{children}<button type="submit" disabled={pending}>{pending ? 'در حال انجام…' : success}</button>{message && <small role={message.type === 'error' ? 'alert' : 'status'} className={`comp-message is-${message.type}`}>{message.text}</small>}</form>;
}

export function CompensationCenterClient({ employeeId, access, items, damages, audits, readiness }: { employeeId: string; access: Access; items: FinancialItem[]; damages: Damage[]; audits: Audit[]; readiness: { label: string; value: string }[] }) {
  const [from, setFrom] = useState(''); const [to, setTo] = useState(''); const [type, setType] = useState(''); const [status, setStatus] = useState('');
  const filtered = items.filter((item) => (!from || item.effectiveDate >= from) && (!to || item.effectiveDate.slice(0, 10) <= to) && (!type || item.type === type) && (!status || item.status === status));
  return <div className="comp-stack">
    <section className="panel-card comp-readiness"><div className="comp-section-head"><div><p className="eyebrow">نمای کلی فقط خواندنی</p><h2>آمادگی تسویه</h2></div>{access.canExport && <a className="button" href={`/employees/${employeeId}/compensation/export`}>دریافت CSV</a>}</div><div className="comp-metrics">{readiness.map((item) => <article key={item.label}><span>{item.label}</span><strong>{item.value}</strong></article>)}</div></section>

    {access.canManageFinancial && <ActionForm action={createEmployeeFinancialItem} confirmText="آیتم مالی جدید ثبت شود؟" success="ثبت آیتم" className="panel-card comp-form"><h2>ثبت آیتم مالی</h2><input type="hidden" name="employeeId" value={employeeId}/><label>عنوان *<input name="title" required/></label><label>مبلغ (ریال) *<input name="amount" required type="number" min="1"/></label><label>تاریخ اثرگذاری *<input name="effectiveDate" required type="date"/></label><label>نوع *<select name="type" required><option value="">انتخاب کنید</option>{['PAYMENT','BONUS','ALLOWANCE','MISSION_PAYMENT','WELFARE_PAYMENT','MEDICAL_SUPPORT','DEDUCTION','LOAN','ADVANCE','DAMAGE','FINE'].map((value)=><option key={value}>{value}</option>)}</select></label><label>نحوه اعمال *<select name="applyMethod" required><option value="THIS_PAYROLL">این دوره حقوق</option><option value="NEXT_PAYROLL">دوره بعد</option><option value="INSTALLMENT">اقساط</option><option value="DIRECT_PAYMENT">پرداخت مستقیم</option><option value="OUTSIDE_PAYROLL">خارج از حقوق</option></select></label><label className="comp-span">شرح<textarea name="description"/></label></ActionForm>}

    <section className="panel-card"><div className="comp-section-head"><div><p className="eyebrow">گردش کار</p><h2>آیتم‌های مالی</h2></div></div>{items.length ? <div className="comp-list">{items.map((item)=><article className="comp-item" key={item.id}><div><span className="comp-status">{statusLabel[item.status] ?? item.status}</span><h3>{item.title}</h3><p>{access.canViewAmounts ? money(item.amount) : 'مبلغ برای نقش شما پنهان است'} · {date(item.effectiveDate)}</p></div><div className="comp-actions">
      {item.status === 'DRAFT' && access.canManageFinancial && <><details><summary>ویرایش</summary><ActionForm action={updateEmployeeFinancialItem} confirmText="تغییرات ذخیره شود؟" success="ذخیره"><input type="hidden" name="itemId" value={item.id}/><label>عنوان<input name="title" defaultValue={item.title} required/></label><label>مبلغ<input name="amount" type="number" min="1" defaultValue={item.amount} required/></label><label>شرح<textarea name="description" defaultValue={item.description ?? ''}/></label></ActionForm></details><ActionForm action={submitFinancialItemForApproval} confirmText="برای تأیید ارسال شود؟" success="ارسال برای تأیید"><input type="hidden" name="itemId" value={item.id}/></ActionForm><ActionForm action={cancelFinancialItem} confirmText="آیتم لغو شود؟" success="لغو"><input type="hidden" name="itemId" value={item.id}/></ActionForm></>}
      {item.status === 'PENDING_APPROVAL' && access.canApproveFinancial && <><ActionForm action={approveFinancialItem} confirmText="آیتم تأیید شود؟" success="تأیید"><input type="hidden" name="itemId" value={item.id}/></ActionForm><ActionForm action={rejectFinancialItem} confirmText="آیتم رد شود؟" success="رد"><input type="hidden" name="itemId" value={item.id}/><input name="reason" required placeholder="دلیل رد"/></ActionForm></>}
      {item.status === 'APPROVED' && access.canFinance && <ActionForm action={applyFinancialItemToPayroll} confirmText="در Payroll اعمال شود؟" success="اعمال در حقوق"><input type="hidden" name="itemId" value={item.id}/><input name="payrollPeriod" placeholder="دوره حقوق"/></ActionForm>}
      {item.status === 'APPLIED_TO_PAYROLL' && access.canFinance && <ActionForm action={markFinancialItemPaid} confirmText="پرداخت ثبت شود؟" success="ثبت پرداخت"><input type="hidden" name="itemId" value={item.id}/><input name="paymentReference" placeholder="شماره پیگیری"/></ActionForm>}
      {item.status === 'PAID' && access.canFinance && <ActionForm action={settleFinancialItem} confirmText="آیتم تسویه شود؟" success="تسویه"><input type="hidden" name="itemId" value={item.id}/></ActionForm>}
    </div></article>)}</div> : <p className="comp-empty">آیتم مالی ثبت نشده است.</p>}</section>

    <section className="panel-card"><div className="comp-section-head"><div><p className="eyebrow">خسارت و رسیدگی</p><h2>خسارت‌ها و اعتراضات مالی</h2></div></div>{access.canManageDamage && <ActionForm action={createEmployeeDamage} confirmText="خسارت ثبت شود؟" success="ثبت خسارت" className="comp-form comp-subform"><input type="hidden" name="employeeId" value={employeeId}/><label>عنوان *<input name="title" required/></label><label>مبلغ *<input name="amount" type="number" min="1" required/></label><label>تاریخ وقوع *<input name="incidentDate" type="date" required/></label><label>تاریخ اثرگذاری *<input name="effectiveDate" type="date" required/></label><label className="comp-span">دلیل/شرح *<textarea name="description" required/></label><label className="comp-span">مستندات (نشانی/شناسه فایل)<input name="documents"/></label></ActionForm>}
      <div className="comp-list">{damages.map((damage)=><article className="comp-item comp-damage" key={damage.id}><div><span className="comp-status">{statusLabel[damage.status] ?? damage.status}</span><h3>{damage.title}</h3><p>{access.canViewAmounts ? money(damage.amount) : 'مبلغ پنهان'} · وقوع {date(damage.incidentDate)}</p><p>{damage.description}</p>{damage.documentReference && <a href={damage.documentReference}>مستندات خسارت</a>}</div><div className="comp-actions">{access.canManageDamage && damage.status === 'DRAFT' && <ActionForm action={submitDamage} confirmText="خسارت برای بررسی ارسال شود؟" success="ارسال بررسی"><input type="hidden" name="damageId" value={damage.id}/></ActionForm>}{access.canManageDamage && damage.status === 'PENDING_REVIEW' && <><ActionForm action={approveDamage} confirmText="خسارت تأیید شود؟" success="تأیید"><input type="hidden" name="damageId" value={damage.id}/></ActionForm><ActionForm action={rejectDamage} confirmText="خسارت رد شود؟" success="رد"><input type="hidden" name="damageId" value={damage.id}/></ActionForm></>}{access.canManageDamage && damage.status === 'APPROVED' && <ActionForm action={applyDamage} confirmText="خسارت اعمال شود؟" success="اعمال"><input type="hidden" name="damageId" value={damage.id}/></ActionForm>}{access.canManageDamage && damage.status === 'APPLIED' && <ActionForm action={closeDamage} confirmText="پرونده خسارت بسته شود؟" success="بستن"><input type="hidden" name="damageId" value={damage.id}/></ActionForm>}</div>
        {access.canCreateObjection && !damage.objections.some((o)=>!['REJECTED','CLOSED'].includes(o.status)) && <ActionForm action={createDamageObjection} confirmText="اعتراض ثبت شود؟" success="ثبت اعتراض" className="comp-objection-form"><input type="hidden" name="damageId" value={damage.id}/><label>شرح اعتراض *<textarea name="description" required/></label><label>فایل/مستندات<input name="documents"/></label></ActionForm>}
        {damage.objections.map((objection)=><div className="comp-objection" key={objection.id}><strong>اعتراض · {statusLabel[objection.status] ?? objection.status}</strong><p>{objection.description}</p>{objection.documents && <a href={objection.documents}>مشاهده فایل</a>}<div className="comp-actions">{access.canReviewObjection && objection.status === 'SUBMITTED' && <ActionForm action={reviewObjection} confirmText="بررسی اعتراض آغاز شود؟" success="بررسی"><input type="hidden" name="objectionId" value={objection.id}/></ActionForm>}{access.canReviewObjection && objection.status === 'UNDER_REVIEW' && <><ActionForm action={approveObjection} confirmText="اعتراض تأیید شود؟" success="تأیید"><input type="hidden" name="objectionId" value={objection.id}/></ActionForm><ActionForm action={rejectObjection} confirmText="اعتراض رد شود؟" success="رد"><input type="hidden" name="objectionId" value={objection.id}/></ActionForm></>}{access.canReviewObjection && ['APPROVED','REJECTED'].includes(objection.status) && <ActionForm action={closeObjection} confirmText="اعتراض بسته شود؟" success="بستن"><input type="hidden" name="objectionId" value={objection.id}/></ActionForm>}</div></div>)}</article>)}</div>{!damages.length && <p className="comp-empty">خسارتی ثبت نشده است.</p>}</section>

    <section className="panel-card"><div className="comp-section-head"><div><p className="eyebrow">گزارش</p><h2>گزارش مالی کارمند</h2></div></div><div className="comp-filters"><label>تاریخ شروع<input type="date" value={from} onChange={(e)=>setFrom(e.target.value)}/></label><label>تاریخ پایان<input type="date" value={to} onChange={(e)=>setTo(e.target.value)}/></label><label>نوع<select value={type} onChange={(e)=>setType(e.target.value)}><option value="">همه</option>{[...new Set(items.map((i)=>i.type))].map((value)=><option key={value}>{value}</option>)}</select></label><label>وضعیت<select value={status} onChange={(e)=>setStatus(e.target.value)}><option value="">همه</option>{[...new Set(items.map((i)=>i.status))].map((value)=><option key={value}>{statusLabel[value] ?? value}</option>)}</select></label></div><div className="comp-report">{filtered.map((item)=><div key={item.id}><strong>{item.title}</strong><span>{item.type}</span><span>{statusLabel[item.status] ?? item.status}</span><b>{access.canViewAmounts ? money(item.amount) : 'محرمانه'}</b></div>)}</div>{!filtered.length && <p className="comp-empty">نتیجه‌ای مطابق فیلترها وجود ندارد.</p>}</section>

    <section className="panel-card"><div className="comp-section-head"><div><p className="eyebrow">EmployeeAuditLog</p><h2>تاریخچه عملیات مالی</h2></div></div><ol className="comp-timeline">{audits.map((log)=><li key={log.id}><span className="comp-timeline-dot"/><div><strong>{actionLabel[log.action] ?? log.action}</strong><p>{date(log.createdAt)} · {log.actor}</p><small>{log.oldStatus ? statusLabel[log.oldStatus] ?? log.oldStatus : '—'} ← {log.newStatus ? statusLabel[log.newStatus] ?? log.newStatus : '—'}</small></div></li>)}</ol>{!audits.length && <p className="comp-empty">رویداد مالی ثبت نشده است.</p>}</section>
  </div>;
}
