import Link from 'next/link';
import { prisma } from '../../../../lib/prisma';
import { getEmployeeCompensationAccess } from '../../../../lib/employee-compensation-access';
import { CompensationCenterClient } from './CompensationCenterClient';

function statusFromJson(value: string | null) { try { const parsed = JSON.parse(value ?? '{}') as { status?: string }; return parsed.status ?? null; } catch { return null; } }
const sum = (values: { amount: { toString(): string } }[]) => values.reduce((total, item) => total + Number(item.amount), 0);
const amountFa = (value: number) => `${new Intl.NumberFormat('fa-IR').format(value)} ریال`;

export default async function EmployeeCompensationPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params; const access = await getEmployeeCompensationAccess(id);
  if (!access.tenantId || !access.canView) return <main className="module-page comp-denied" dir="rtl"><h1>دسترسی غیرمجاز</h1><p>اجازه مشاهده مرکز جبران خدمات این کارمند را ندارید.</p><Link className="button" href="/employees">بازگشت به کارکنان</Link></main>;
  const employee = await prisma.employee.findFirst({ where: { id, tenantId: access.tenantId }, select: { firstName: true, lastName: true, financialItems: { orderBy: { effectiveDate: 'desc' } }, damages: { orderBy: { createdAt: 'desc' }, include: { objections: { orderBy: { createdAt: 'desc' } } } }, requests: { where: { requestType: { in: ['loan', 'salary_advance'] } }, select: { requestType: true, status: true, amount: true } }, auditLogs: { where: { source: 'employee_compensation' }, orderBy: { createdAt: 'desc' }, take: 100 } } });
  if (!employee) return <main className="module-page" dir="rtl"><h1>کارمند یافت نشد</h1></main>;
  const actorIds = [...new Set(employee.auditLogs.map((log) => log.actorUserId).filter((value): value is string => Boolean(value)))];
  const actors = actorIds.length ? await prisma.appUser.findMany({ where: { id: { in: actorIds } }, select: { id: true, fullName: true } }) : [];
  const actorNames = new Map(actors.map((actor) => [actor.id, actor.fullName]));
  const openLoans = employee.requests.filter((request) => request.requestType === 'loan' && !['rejected', 'cancelled', 'closed'].includes(String(request.status)));
  const openAdvances = employee.requests.filter((request) => request.requestType === 'salary_advance' && !['rejected', 'cancelled', 'closed'].includes(String(request.status)));
  const openDamages = employee.damages.filter((damage) => !['REJECTED', 'CLOSED'].includes(damage.status));
  const openObjections = employee.damages.flatMap((damage) => damage.objections).filter((objection) => !['REJECTED', 'CLOSED'].includes(objection.status));
  const unpaid = employee.financialItems.filter((item) => !['PAID', 'SETTLED', 'CANCELLED', 'REJECTED'].includes(item.status));
  const unpaidBenefits = unpaid.filter((item) => ['BONUS', 'ALLOWANCE', 'MISSION_PAYMENT', 'WELFARE_PAYMENT', 'MEDICAL_SUPPORT', 'OTHER_PAYMENT'].includes(item.type));
  const activeDebt = unpaid.filter((item) => ['DEDUCTION', 'LOAN', 'ADVANCE', 'DAMAGE', 'FINE', 'OTHER_DEDUCTION'].includes(item.type));
  return <main className="module-page compensation-center" dir="rtl"><header className="module-page__header"><div><p className="eyebrow">پرونده کارمند</p><h1>حقوق، مزایا و تعهدات مالی</h1><p>{employee.firstName} {employee.lastName}</p></div><Link className="button button--ghost" href={`/employees/${id}`}>بازگشت به پروفایل</Link></header><CompensationCenterClient employeeId={id} access={{ canViewAmounts: access.canViewAmounts, canManageFinancial: access.canManageFinancial, canApproveFinancial: access.canApproveFinancial, canManageDamage: access.canManageDamage, canCreateObjection: access.canCreateObjection, canReviewObjection: access.canReviewObjection, canFinance: access.canFinance, canExport: access.canExport }} items={employee.financialItems.map((item)=>({ id: item.id, title: item.title, amount: item.amount.toString(), type: item.type, status: item.status, description: item.description, effectiveDate: item.effectiveDate.toISOString(), paymentAmount: item.paymentAmount?.toString() ?? null }))} damages={employee.damages.map((damage)=>({ id: damage.id, title: damage.title, description: damage.description, amount: damage.amount.toString(), status: damage.status, incidentDate: damage.incidentDate.toISOString(), effectiveDate: damage.effectiveDate.toISOString(), documentReference: damage.documentReference, objections: damage.objections.map((objection)=>({ id: objection.id, description: objection.description, documents: objection.documents, status: objection.status, createdAt: objection.createdAt.toISOString() })) }))} audits={employee.auditLogs.map((log)=>({ id: log.id, action: log.action, oldStatus: statusFromJson(log.oldValue), newStatus: statusFromJson(log.newValue), actor: log.actorUserId ? actorNames.get(log.actorUserId) ?? log.actorRole ?? 'کاربر سامانه' : 'سامانه', createdAt: log.createdAt.toISOString() }))} readiness={[{ label: 'مانده وام', value: amountFa(sum(openLoans.filter((item): item is typeof item & { amount: NonNullable<typeof item.amount> } => item.amount !== null) as never)) }, { label: 'مانده مساعده', value: amountFa(sum(openAdvances.filter((item): item is typeof item & { amount: NonNullable<typeof item.amount> } => item.amount !== null) as never)) }, { label: 'بدهی فعال', value: amountFa(sum(activeDebt)) }, { label: 'خسارت باز', value: `${openDamages.length} مورد` }, { label: 'اعتراض باز', value: `${openObjections.length} مورد` }, { label: 'پرداخت‌نشده', value: amountFa(sum(unpaid)) }, { label: 'مزایای پرداخت‌نشده', value: amountFa(sum(unpaidBenefits)) }]} /></main>;
}
