services:
  vahedyek-panel:
    image: vahedyek-panel:latest
    container_name: vahedyek-panel
    build:
      context: apps/vahedyek-panel/
      dockerfile: apps/vahedyek-panel/Dockerfile
    restart: unless-stopped

  dastranj-panel:
    image: dastranj-panel:latest
    container_name: dastranj-panel
    build:
      context: apps/dastranj-panel/
      dockerfile: apps/dastranj-panel/Dockerfile
    restart: unless-stopped
