services:
  dastranj-db:
    image: postgres:18
    container_name: dastranj-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: dastranj
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "55432:5432"
    volumes:
      - dastranj-postgres-data:/var/lib/postgresql

  vahedyek-panel:
    image: vahedyek-panel:latest
    container_name: vahedyek-panel
    build:
      context: .
      dockerfile: apps/vahedyek-panel/Dockerfile
    restart: unless-stopped

  dastranj-panel:
    image: dastranj-panel:latest
    container_name: dastranj-panel
    build:
      context: .
      dockerfile: apps/dastranj-panel/Dockerfile
    restart: unless-stopped

  ai-lab:
    image: ai-lab:latest
    container_name: ai-lab
    build:
      context: .
      dockerfile: apps/taav-ai-lab/Dockerfile
    restart: unless-stopped

volumes:
  dastranj-postgres-data:
