import Link from 'next/link';
import { prisma } from '../../../lib/prisma';
import { getJobClassificationAccess } from '../../../lib/organization-unit-access';

export default async function JobClassificationReportsPage() {
  const access = await getJobClassificationAccess();
  if (!access.tenantId || !access.canView) return <main className="module-page"><div className="module-empty-state"><h1>دسترسی ندارید</h1></div></main>;
  const [families, categories, levels, classifications, profiles, evaluations, ranges] = await Promise.all([
    prisma.jobFamily.count({ where: { tenantId: access.tenantId } }), prisma.jobCategory.count({ where: { tenantId: access.tenantId } }), prisma.jobLevel.count({ where: { tenantId: access.tenantId } }),
    prisma.jobClassification.findMany({ where: { tenantId: access.tenantId, status: 'ACTIVE' }, include: { jobProfile: { select: { title: true, code: true, positions: { select: { id: true } } } }, family: { select: { name: true } }, category: { select: { name: true } }, level: { select: { name: true } }, grade: { select: { name: true } }, rank: { select: { name: true } } }, orderBy: { createdAt: 'desc' } }),
    prisma.jobProfile.findMany({ where: { tenantId: access.tenantId, status: 'ACTIVE', classifications: { none: { status: 'ACTIVE' } } }, select: { id: true, title: true, code: true, positions: { select: { id: true } } }, orderBy: { title: 'asc' } }),
    prisma.jobEvaluation.findMany({ where: { tenantId: access.tenantId, status: 'ACTIVE' }, include: { jobProfile: { select: { title: true } } }, orderBy: { createdAt: 'desc' } }),
    prisma.jobCompensationRange.findMany({ where: { tenantId: access.tenantId, status: 'ACTIVE' }, include: { classification: { include: { jobProfile: { select: { title: true } } } }, grade: { select: { name: true } } }, orderBy: { effectiveFrom: 'desc' } }),
  ]);
  return <main className="page-stack module-page" dir="rtl"><header className="module-page-header"><div><p className="module-page-eyebrow">گزارش معماری شغل</p><h1>گزارش طبقه‌بندی‌های شغلی</h1><p>طبقه‌بندی، ارزیابی و بازه‌های پیشنهادی جبران خدمت.</p></div><Link href="/job-classifications">بازگشت به طبقه‌بندی‌ها</Link></header><section className="module-page-grid">{[['خانواده', families], ['دسته', categories], ['سطح', levels], ['طبقه‌بندی', classifications.length]].map(([label, count]) => <article className="module-grid-card" key={String(label)}><h2>{label}</h2><strong>{count}</strong></article>)}</section><section className="org-profile-card"><h2>گزارش طبقه‌بندی</h2>{classifications.length ? <div className="module-page-grid">{classifications.map((item) => <article className="module-grid-card" key={item.id}><h3>{item.jobProfile.title}</h3><p>{item.family.name} / {item.category?.name ?? 'بدون دسته'} / {item.level.name} / {item.grade?.name ?? 'بدون گرید'} / {item.rank?.name ?? 'بدون رتبه'}</p><p>Job Profile: 1 · Position: {item.jobProfile.positions.length}</p></article>)}</div> : <div className="module-empty-state"><p>طبقه‌بندی فعالی وجود ندارد.</p></div>}</section><section className="org-profile-card"><h2>گزارش ارزیابی</h2>{evaluations.length ? <ul>{evaluations.map((item) => <li key={item.id}>{item.jobProfile.title}: {item.totalScore?.toString() ?? '—'} · {item.approvedAt ? 'تأییدشده' : 'در انتظار تأیید'}</li>)}</ul> : <div className="module-empty-state"><p>ارزیابی ثبت نشده است.</p></div>}</section><section className="org-profile-card"><h2>گزارش بازه جبران خدمت</h2>{ranges.length ? <ul>{ranges.map((range) => <li key={range.id}>{range.classification.jobProfile.title} · {range.grade.name}: {Number(range.minimumAmount).toLocaleString('fa-IR')} تا {Number(range.maximumAmount).toLocaleString('fa-IR')} {range.currency}</li>)}</ul> : <div className="module-empty-state"><p>بازه فعالی ثبت نشده است.</p></div>}</section><section className="org-profile-card"><h2>Missing Classification</h2>{profiles.length ? <ul>{profiles.map((profile) => <li key={profile.id}>{profile.title}{profile.code ? ` · ${profile.code}` : ''} — {profile.positions.length} سمت</li>)}</ul> : <div className="module-empty-state"><p>همه پروفایل‌های فعال دارای طبقه‌بندی هستند.</p></div>}</section></main>;
}
