'use client';

import Link from 'next/link';
import { Archive, Download, ExternalLink, FileClock, FilePlus2, Files, Search, ShieldCheck, Upload, X } from 'lucide-react';
import { useActionState, useEffect, useState } from 'react';
import { archiveEmployeeDocumentAction, createEmployeeDocumentAction, type EmployeeDocumentActionState } from '../../../../../lib/employee-document-actions';

type DocumentItem = {
  id: string; title: string; documentType: string; category: string; subCategory: string | null; documentDate: string; documentNumber: string | null;
  status: string; versionNumber: number; sourceType: string; sourceModule: string; sourceHref: string | null; accessLevel: string;
  isCurrentVersion: boolean; expiresAt: string | null; createdBy: string | null; attachment: { fileName: string; fileType: string | null; fileSize: number | null } | null;
  _count: { versions: number; auditLogs: number };
};

const STATUS_LABELS: Record<string, string> = { DRAFT: 'پیش‌نویس', PENDING_APPROVAL: 'در انتظار تأیید', FINAL: 'نهایی', REJECTED: 'ردشده', EXPIRED: 'منقضی', REPLACED: 'جایگزین‌شده', ARCHIVED: 'آرشیوشده', VOID: 'باطل' };
const SOURCE_LABELS: Record<string, string> = { CONTRACT: 'قرارداد', PAYROLL: 'حقوق و دستمزد', REQUEST: 'درخواست‌ها', TERMINATION: 'خاتمه همکاری', OTHER: 'ثبت مستقیم' };
const CATEGORY_LABELS: Record<string, string> = { IDENTITY: 'هویتی', EDUCATION: 'آموزشی', EMPLOYMENT: 'استخدامی', REQUESTS: 'درخواست‌ها', FINANCIAL: 'مالی', HEALTH: 'سلامت', ORGANIZATION: 'سازمانی', OTHER: 'سایر' };
const initialState: EmployeeDocumentActionState = { ok: false, message: '' };

function formatSize(value: number | null | undefined) {
  if (!value) return '—';
  return value < 1024 * 1024 ? `${Math.ceil(value / 1024).toLocaleString('fa-IR')} کیلوبایت` : `${(value / 1024 / 1024).toFixed(1).toLocaleString()} مگابایت`;
}

function DocumentForm({ employeeId, categories, parent, onClose }: { employeeId: string; categories: Record<string, readonly string[]>; parent: DocumentItem | null; onClose: () => void }) {
  const [state, action, pending] = useActionState(createEmployeeDocumentAction, initialState);
  const [category, setCategory] = useState(parent?.category ?? 'IDENTITY');
  useEffect(() => { if (state.ok) { const timer = setTimeout(onClose, 700); return () => clearTimeout(timer); } }, [state.ok, onClose]);
  return <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/50 p-4" role="dialog" aria-modal="true" aria-labelledby="document-form-title">
    <div className="max-h-[92dvh] w-full max-w-3xl overflow-y-auto rounded-2xl bg-white p-5 shadow-2xl">
      <div className="flex items-start justify-between gap-4"><div><h2 id="document-form-title" className="text-lg font-bold">{parent ? `نسخه جدید «${parent.title}»` : 'افزودن سند مستقیم'}</h2><p className="mt-1 text-sm text-slate-500">فایل قبلی بازنویسی نمی‌شود و هر نسخه در تاریخچه باقی می‌ماند.</p></div><button type="button" onClick={onClose} aria-label="بستن" className="grid min-h-11 min-w-11 place-items-center rounded-xl hover:bg-slate-100"><X className="h-5 w-5"/></button></div>
      <form action={action} className="mt-5 grid gap-4 md:grid-cols-2" encType="multipart/form-data">
        <input type="hidden" name="employeeId" value={employeeId}/><input type="hidden" name="parentDocumentId" value={parent?.id ?? ''}/>
        <label className="grid gap-1.5 text-sm">عنوان سند *<input name="title" required defaultValue={parent?.title} className="min-h-11 rounded-xl border border-slate-300 px-3"/></label>
        <label className="grid gap-1.5 text-sm">دسته *<select name="category" value={category} onChange={(event) => setCategory(event.target.value)} className="min-h-11 rounded-xl border border-slate-300 bg-white px-3">{Object.keys(categories).map((key) => <option key={key} value={key}>{CATEGORY_LABELS[key]}</option>)}</select></label>
        <label className="grid gap-1.5 text-sm">نوع سند *<select name="documentType" required defaultValue={parent?.documentType ?? categories[category]?.[0]} className="min-h-11 rounded-xl border border-slate-300 bg-white px-3">{categories[category]?.map((item) => <option key={item}>{item}</option>)}</select></label>
        <label className="grid gap-1.5 text-sm">زیرگروه<input name="subCategory" defaultValue={parent?.subCategory ?? ''} className="min-h-11 rounded-xl border border-slate-300 px-3"/></label>
        <label className="grid gap-1.5 text-sm">تاریخ سند *<input type="date" name="documentDate" required defaultValue={parent?.documentDate} className="min-h-11 rounded-xl border border-slate-300 px-3"/></label>
        <label className="grid gap-1.5 text-sm">تاریخ انقضا<input type="date" name="expiresAt" defaultValue={parent?.expiresAt ?? ''} className="min-h-11 rounded-xl border border-slate-300 px-3"/></label>
        <label className="grid gap-1.5 text-sm">شماره سند<input name="documentNumber" defaultValue={parent?.documentNumber ?? ''} className="min-h-11 rounded-xl border border-slate-300 px-3"/></label>
        <label className="grid gap-1.5 text-sm">سطح دسترسی *<select name="accessLevel" required defaultValue={parent?.accessLevel ?? 'HR'} className="min-h-11 rounded-xl border border-slate-300 bg-white px-3"><option value="PRIVATE">فقط مدیر پرونده</option><option value="EMPLOYEE">کارمند</option><option value="MANAGERS">مدیر مستقیم</option><option value="HR">منابع انسانی</option><option value="FINANCIAL">مالی</option></select></label>
        <label className="grid gap-1.5 text-sm md:col-span-2">برچسب‌ها<input name="tags" placeholder="با ویرگول جدا کنید" className="min-h-11 rounded-xl border border-slate-300 px-3"/></label>
        <label className="grid gap-1.5 text-sm md:col-span-2">توضیحات<textarea name="description" rows={3} className="rounded-xl border border-slate-300 p-3"/></label>
        {parent && <label className="grid gap-1.5 text-sm md:col-span-2">دلیل نسخه جدید *<textarea name="versionReason" required rows={2} className="rounded-xl border border-slate-300 p-3"/></label>}
        <label className="grid gap-1.5 text-sm md:col-span-2">فایل *<input type="file" name="file" required accept="application/pdf,image/jpeg,image/png,image/webp" className="min-h-11 rounded-xl border border-dashed border-slate-400 p-3"/><span className="text-xs text-slate-500">PDF یا تصویر، حداکثر ۱۰ مگابایت</span></label>
        {state.message && <p className={`md:col-span-2 rounded-xl p-3 text-sm ${state.ok ? 'bg-emerald-50 text-emerald-800' : 'bg-rose-50 text-rose-800'}`} role={state.ok ? 'status' : 'alert'}>{state.message}</p>}
        <div className="flex gap-2 md:col-span-2"><button disabled={pending} className="min-h-11 rounded-xl bg-slate-900 px-5 font-semibold text-white disabled:opacity-50">{pending ? 'در حال ثبت…' : parent ? 'ثبت نسخه جدید' : 'ثبت سند'}</button><button type="button" onClick={onClose} className="min-h-11 rounded-xl border border-slate-300 px-5">انصراف</button></div>
      </form>
    </div>
  </div>;
}

export function EmployeeDocumentCenterClient({ employeeId, documents, categories, permissions }: { employeeId: string; documents: DocumentItem[]; categories: Record<string, readonly string[]>; permissions: { canUpload: boolean; canEdit: boolean; canArchive: boolean; canDownload: boolean } }) {
  const [formOpen, setFormOpen] = useState(false);
  const [formParent, setFormParent] = useState<DocumentItem | null>(null);
  const openForm = (parent: DocumentItem | null) => { setFormParent(parent); setFormOpen(true); };
  const current = documents.filter((item) => item.isCurrentVersion && item.status !== 'ARCHIVED');
  const archived = documents.filter((item) => item.status === 'ARCHIVED').length;
  const system = documents.filter((item) => item.sourceType === 'MODULE_GENERATED').length;
  return <>
    <section className="grid gap-3 sm:grid-cols-3"><div className="rounded-2xl border border-slate-200 bg-white p-4"><Files className="h-5 w-5 text-sky-600"/><strong className="mt-3 block text-2xl">{current.length.toLocaleString('fa-IR')}</strong><span className="text-sm text-slate-500">اسناد جاری</span></div><div className="rounded-2xl border border-slate-200 bg-white p-4"><FileClock className="h-5 w-5 text-violet-600"/><strong className="mt-3 block text-2xl">{system.toLocaleString('fa-IR')}</strong><span className="text-sm text-slate-500">اسناد سیستمی</span></div><div className="rounded-2xl border border-slate-200 bg-white p-4"><Archive className="h-5 w-5 text-amber-600"/><strong className="mt-3 block text-2xl">{archived.toLocaleString('fa-IR')}</strong><span className="text-sm text-slate-500">آرشیوشده</span></div></section>
    <section className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><h2 className="font-bold">دسته‌بندی اسناد</h2><div className="mt-3 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{Object.entries(categories).map(([category, types]) => <details key={category} className="rounded-xl border border-slate-200 p-3"><summary className="cursor-pointer font-semibold">{CATEGORY_LABELS[category]}</summary><div className="mt-2 grid gap-1">{types.map((type) => <a key={type} href={`?category=${encodeURIComponent(category)}&q=${encodeURIComponent(type)}`} className="rounded-lg px-2 py-1.5 text-sm text-slate-600 hover:bg-slate-50">{type}</a>)}</div><a href={`?category=${encodeURIComponent(category)}`} className="mt-2 inline-block text-xs font-semibold text-sky-700">مشاهده همه این دسته</a></details>)}</div></section>
    <section className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><form className="grid gap-3 md:grid-cols-2 xl:grid-cols-8"><label className="relative xl:col-span-2"><Search className="absolute right-3 top-3.5 h-4 w-4 text-slate-400"/><span className="sr-only">جستجو</span><input name="q" placeholder="عنوان، شماره یا نوع سند" className="min-h-11 w-full rounded-xl border border-slate-300 pr-10 pl-3"/></label><select name="category" aria-label="دسته" className="min-h-11 rounded-xl border border-slate-300 bg-white px-3"><option value="">همه دسته‌ها</option>{Object.keys(categories).map((key) => <option key={key} value={key}>{CATEGORY_LABELS[key]}</option>)}</select><select name="status" aria-label="وضعیت" className="min-h-11 rounded-xl border border-slate-300 bg-white px-3"><option value="">همه وضعیت‌ها</option>{Object.entries(STATUS_LABELS).map(([key,label]) => <option key={key} value={key}>{label}</option>)}</select><select name="sourceModule" aria-label="ماژول منبع" className="min-h-11 rounded-xl border border-slate-300 bg-white px-3"><option value="">همه منابع</option>{Object.entries(SOURCE_LABELS).map(([key,label]) => <option key={key} value={key}>{label}</option>)}</select><label className="grid gap-1 text-xs text-slate-500">از تاریخ<input name="dateFrom" type="date" className="min-h-11 rounded-xl border border-slate-300 px-3 text-sm text-slate-900"/></label><label className="grid gap-1 text-xs text-slate-500">تا تاریخ<input name="dateTo" type="date" className="min-h-11 rounded-xl border border-slate-300 px-3 text-sm text-slate-900"/></label><select name="creator" aria-label="ایجادکننده" className="min-h-11 rounded-xl border border-slate-300 bg-white px-3"><option value="">همه ایجادکنندگان</option><option value="EMPLOYEE">کارمند</option><option value="MANAGER">مدیر</option><option value="HR">منابع انسانی</option><option value="SYSTEM">سیستم</option><option value="MODULE">ماژول</option></select><button className="min-h-11 rounded-xl border border-slate-300 font-semibold hover:bg-slate-50">اعمال فیلتر</button></form></section>
    <section className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-lg font-bold">اسناد پرونده</h2><p className="text-sm text-slate-500">نسخه‌های قبلی حذف نمی‌شوند و اسناد سیستمی فقط در ماژول مرجع ویرایش می‌شوند.</p></div>{permissions.canUpload && <button onClick={() => openForm(null)} className="inline-flex min-h-11 items-center gap-2 rounded-xl bg-slate-900 px-4 font-semibold text-white"><Upload className="h-4 w-4"/>افزودن سند</button>}</section>
    {documents.length === 0 ? <section className="rounded-2xl border border-dashed border-slate-300 bg-white p-10 text-center"><FilePlus2 className="mx-auto h-9 w-9 text-slate-400"/><h2 className="mt-3 font-bold">هنوز سندی ثبت نشده است</h2><p className="mt-1 text-sm text-slate-500">اسناد مستقیم را اضافه کنید؛ مراجع ماژول‌ها نیز بدون کپی شدن اینجا ظاهر می‌شوند.</p></section> : <section className="space-y-3">{documents.map((document) => <article key={document.id} className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-4"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><h3 className="font-bold text-slate-900">{document.title}</h3><span className="rounded-full bg-slate-100 px-2.5 py-1 text-xs">{STATUS_LABELS[document.status]}</span>{['IDENTITY','HEALTH','FINANCIAL'].includes(document.category) && <span className="inline-flex items-center gap-1 rounded-full bg-rose-50 px-2.5 py-1 text-xs text-rose-700"><ShieldCheck className="h-3 w-3"/>حساس</span>}</div><p className="mt-2 text-sm text-slate-600">{document.documentType} · {CATEGORY_LABELS[document.category]} · نسخه {document.versionNumber.toLocaleString('fa-IR')} · {SOURCE_LABELS[document.sourceModule]}</p><p className="mt-1 text-xs text-slate-500">تاریخ سند: {document.documentDate} {document.attachment ? `· ${document.attachment.fileName} · ${formatSize(document.attachment.fileSize)}` : '· فایل در ماژول مرجع نگهداری می‌شود'}</p></div><div className="flex flex-wrap gap-2"><Link href={`/employees/${employeeId}/documents/${document.id}`} className="inline-flex min-h-11 items-center rounded-xl border border-slate-300 px-3 text-sm font-semibold">جزئیات</Link>{document.attachment && permissions.canDownload && <a href={`/api/employees/${employeeId}/documents/${document.id}/download`} className="inline-flex min-h-11 items-center gap-1 rounded-xl border border-slate-300 px-3 text-sm font-semibold"><Download className="h-4 w-4"/>دانلود</a>}{document.sourceHref && <Link href={document.sourceHref} className="inline-flex min-h-11 items-center gap-1 rounded-xl border border-slate-300 px-3 text-sm font-semibold"><ExternalLink className="h-4 w-4"/>ماژول مرجع</Link>}{document.sourceType === 'DIRECT_UPLOAD' && document.isCurrentVersion && permissions.canEdit && <button onClick={() => openForm(document)} className="min-h-11 rounded-xl border border-slate-300 px-3 text-sm font-semibold">نسخه جدید</button>}{permissions.canArchive && <form action={archiveEmployeeDocumentAction}><input type="hidden" name="employeeId" value={employeeId}/><input type="hidden" name="documentId" value={document.id}/><input type="hidden" name="restore" value={String(document.status === 'ARCHIVED')}/><button className="min-h-11 rounded-xl border border-slate-300 px-3 text-sm font-semibold">{document.status === 'ARCHIVED' ? 'بازیابی' : 'آرشیو'}</button></form>}</div></div></article>)}</section>}
    {formOpen && <DocumentForm employeeId={employeeId} categories={categories} parent={formParent} onClose={() => setFormOpen(false)}/>} 
  </>;
}
