import Link from 'next/link';
import { Archive, Download, ExternalLink, FileText, History, ShieldCheck } from 'lucide-react';
import { archiveEmployeeDocumentAction, changeEmployeeDocumentPermissionAction, updateEmployeeDocumentMetadataAction } from '../../../../../lib/employee-document-actions';
import { DOCUMENT_CATEGORIES, getEmployeeDocument } from '../../../../../lib/employee-documents';

const labels: Record<string, string> = { DIRECT_UPLOAD: 'ثبت مستقیم', MODULE_GENERATED: 'تولیدشده در ماژول', CONTRACT: 'قرارداد', PAYROLL: 'حقوق و دستمزد', REQUEST: 'درخواست‌ها', TERMINATION: 'خاتمه همکاری', OTHER: 'سایر', FINAL: 'نهایی', ARCHIVED: 'آرشیوشده', REPLACED: 'جایگزین‌شده' };

export default async function EmployeeDocumentDetailPage({ params }: { params: Promise<{ id: string; documentId: string }> }) {
  const { id, documentId } = await params;
  const { document, access } = await getEmployeeDocument(id, documentId);
  return <main className="page-stack" dir="rtl" lang="fa">
    <nav className="text-sm text-slate-500"><Link href={`/employees/${id}/documents`}>مرکز اسناد</Link> / {document.title}</nav>
    <header className="flex flex-wrap items-start justify-between gap-4"><div><div className="flex items-center gap-2"><FileText className="h-6 w-6 text-sky-700"/><h1 className="text-2xl font-bold">{document.title}</h1></div><p className="mt-2 text-sm text-slate-600">{document.documentType} · نسخه {document.versionNumber.toLocaleString('fa-IR')} · {labels[document.status] ?? document.status}</p></div><div className="flex flex-wrap gap-2">{document.attachment && access.canDownload && <a href={`/api/employees/${id}/documents/${document.id}/download`} className="inline-flex min-h-11 items-center gap-2 rounded-xl bg-slate-900 px-4 font-semibold text-white"><Download className="h-4 w-4"/>دانلود</a>}{document.sourceHref && <Link href={document.sourceHref} className="inline-flex min-h-11 items-center gap-2 rounded-xl border border-slate-300 px-4 font-semibold"><ExternalLink className="h-4 w-4"/>ماژول مرجع</Link>}</div></header>
    {document.sourceType === 'MODULE_GENERATED' && <section className="rounded-2xl border border-sky-200 bg-sky-50 p-4 text-sm text-sky-900">این سند در ماژول {labels[document.sourceModule]} تولید شده است. محتوای آن در مرکز اسناد قابل ویرایش نیست؛ برای تغییر به ماژول مرجع مراجعه کنید.</section>}
    <section className="grid gap-4 lg:grid-cols-[1.2fr_.8fr]"><article className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="font-bold">مشخصات سند</h2><dl className="mt-4 grid gap-4 sm:grid-cols-2"><div><dt className="text-xs text-slate-500">دسته</dt><dd className="mt-1 font-medium">{document.category}</dd></div><div><dt className="text-xs text-slate-500">زیرگروه</dt><dd className="mt-1 font-medium">{document.subCategory || '—'}</dd></div><div><dt className="text-xs text-slate-500">شماره سند</dt><dd className="mt-1 font-medium">{document.documentNumber || '—'}</dd></div><div><dt className="text-xs text-slate-500">تاریخ سند</dt><dd className="mt-1 font-medium">{document.documentDate}</dd></div><div><dt className="text-xs text-slate-500">انقضا</dt><dd className="mt-1 font-medium">{document.expiresAt || 'ندارد'}</dd></div><div><dt className="text-xs text-slate-500">سطح دسترسی</dt><dd className="mt-1 inline-flex items-center gap-1 font-medium"><ShieldCheck className="h-4 w-4"/>{document.accessLevel}</dd></div><div className="sm:col-span-2"><dt className="text-xs text-slate-500">توضیحات</dt><dd className="mt-1 leading-7">{document.description || '—'}</dd></div></dl></article><aside className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="font-bold">منبع</h2><p className="mt-4 text-sm">نوع: {labels[document.sourceType]}</p><p className="mt-2 text-sm">ماژول: {labels[document.sourceModule]}</p><p className="mt-2 break-all text-sm">شناسه مرجع: {document.sourceRecordId || '—'}</p>{access.canArchive && <form action={archiveEmployeeDocumentAction} className="mt-5"><input type="hidden" name="employeeId" value={id}/><input type="hidden" name="documentId" value={document.id}/><input type="hidden" name="restore" value={String(document.status === 'ARCHIVED')}/><button className="inline-flex min-h-11 items-center gap-2 rounded-xl border border-amber-300 px-4 text-sm font-semibold text-amber-900"><Archive className="h-4 w-4"/>{document.status === 'ARCHIVED' ? 'بازیابی سند' : 'آرشیو سند'}</button></form>}</aside></section>
    {document.attachment && <section className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="font-bold">پیش‌نمایش فایل</h2><iframe title={`پیش‌نمایش ${document.title}`} src={`/api/employees/${id}/documents/${document.id}/preview`} className="mt-4 h-[34rem] w-full rounded-xl border border-slate-200" sandbox="allow-same-origin"/></section>}
    <section className="grid gap-4 lg:grid-cols-2"><article className="rounded-2xl border border-slate-200 bg-white p-5"><div className="flex items-center gap-2"><History className="h-5 w-5"/><h2 className="font-bold">تاریخچه نسخه‌ها</h2></div><div className="mt-4 space-y-3">{document.parentDocument && <Link className="block rounded-xl border border-slate-200 p-3" href={`/employees/${id}/documents/${document.parentDocument.id}`}>نسخه {document.parentDocument.versionNumber.toLocaleString('fa-IR')} (نسخه مبنا)</Link>}{document.versions.map((version) => <Link key={version.id} className="block rounded-xl border border-slate-200 p-3" href={`/employees/${id}/documents/${version.id}`}><strong>نسخه {version.versionNumber.toLocaleString('fa-IR')}</strong><span className="mt-1 block text-xs text-slate-500">{version.versionReason || 'بدون توضیح'} · {version.status}</span></Link>)}{!document.parentDocument && document.versions.length === 0 && <p className="text-sm text-slate-500">این سند هنوز نسخه دیگری ندارد.</p>}</div></article><article className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="font-bold">خلاصه Audit</h2><div className="mt-4 space-y-3">{document.auditLogs.map((event) => <div key={event.id} className="rounded-xl bg-slate-50 p-3 text-sm"><strong>{event.action}</strong><span className="mt-1 block text-xs text-slate-500">نقش: {event.actorRole || 'system'} · {event.createdAt.toLocaleString('fa-IR')}</span></div>)}{document.auditLogs.length === 0 && <p className="text-sm text-slate-500">رویدادی ثبت نشده است.</p>}</div></article></section>
    {access.canEdit && <section className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="font-bold">ویرایش متادیتا</h2><p className="mt-1 text-sm text-slate-500">فایل اصلی تغییر نمی‌کند و تغییرات در Audit ثبت می‌شوند.</p><form action={updateEmployeeDocumentMetadataAction} className="mt-4 grid gap-3 md:grid-cols-2"><input type="hidden" name="employeeId" value={id}/><input type="hidden" name="documentId" value={document.id}/><label className="grid gap-1 text-sm">عنوان<input name="title" required defaultValue={document.title} className="min-h-11 rounded-xl border border-slate-300 px-3"/></label><label className="grid gap-1 text-sm">دسته<select name="category" defaultValue={document.category} className="min-h-11 rounded-xl border border-slate-300 bg-white px-3">{Object.keys(DOCUMENT_CATEGORIES).map((category) => <option key={category} value={category}>{category}</option>)}</select></label><label className="grid gap-1 text-sm">زیرگروه<input name="subCategory" defaultValue={document.subCategory ?? ''} className="min-h-11 rounded-xl border border-slate-300 px-3"/></label><label className="grid gap-1 text-sm">نوع سند<input name="documentType" required defaultValue={document.documentType} className="min-h-11 rounded-xl border border-slate-300 px-3"/></label><label className="grid gap-1 text-sm">تاریخ سند<input name="documentDate" type="date" required defaultValue={document.documentDate} className="min-h-11 rounded-xl border border-slate-300 px-3"/></label><label className="grid gap-1 text-sm">شماره سند<input name="documentNumber" defaultValue={document.documentNumber ?? ''} className="min-h-11 rounded-xl border border-slate-300 px-3"/></label><label className="grid gap-1 text-sm md:col-span-2">برچسب‌ها<input name="tags" defaultValue={document.tags.join(', ')} className="min-h-11 rounded-xl border border-slate-300 px-3"/></label><label className="grid gap-1 text-sm md:col-span-2">توضیحات<textarea name="description" defaultValue={document.description ?? ''} rows={3} className="rounded-xl border border-slate-300 p-3"/></label><button className="min-h-11 w-fit rounded-xl bg-slate-900 px-5 font-semibold text-white">ذخیره متادیتا</button></form></section>}
    {access.canManage && <section className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="font-bold">تغییر سطح دسترسی</h2><form action={changeEmployeeDocumentPermissionAction} className="mt-4 flex flex-wrap items-end gap-3"><input type="hidden" name="employeeId" value={id}/><input type="hidden" name="documentId" value={document.id}/><label className="grid min-w-64 gap-1 text-sm">سطح دسترسی<select name="accessLevel" defaultValue={document.accessLevel} className="min-h-11 rounded-xl border border-slate-300 bg-white px-3"><option value="PRIVATE">فقط مدیر پرونده</option><option value="EMPLOYEE">کارمند</option><option value="MANAGERS">مدیر مستقیم</option><option value="HR">منابع انسانی</option><option value="FINANCIAL">مالی</option></select></label><button className="min-h-11 rounded-xl border border-slate-300 px-5 font-semibold">اعمال دسترسی</button></form></section>}
  </main>;
}
