'use server';
import { revalidatePath } from 'next/cache';
import { prisma } from './prisma';
import { getSessionContext } from './auth';
import { getEmployeeAssessmentAccess } from './organization-unit-access';

const text = (v: FormDataEntryValue | null) => String(v ?? '').trim();
async function audit(tenantId: string, employeeId: string, assessmentId: string, action: string, actorUserId?: string, before?: unknown, after?: unknown) {
  await prisma.employeeAssessmentAuditLog.create({ data: { tenantId, employeeId, assessmentId, action, actorUserId, oldValue: before as any, newValue: after as any } });
}
export async function createEmployeeAssessmentAction(formData: FormData) {
  const employeeId = text(formData.get('employeeId')); const access = await getEmployeeAssessmentAccess(employeeId); const session = await getSessionContext();
  if (!access.tenantId || !access.canCreate || text(formData.get('type')) === 'RECRUITMENT') throw new Error('اجازه ایجاد ارزیابی وجود ندارد.');
  const title = text(formData.get('title')); if (!title) throw new Error('عنوان ارزیابی الزامی است.');
  const criteria = JSON.parse(text(formData.get('criteriaJson')) || '[]') as Array<{title:string;description?:string;weight?:number;score?:number;evidence?:string}>;
  if (!criteria.length) throw new Error('حداقل یک معیار الزامی است.');
  const assessment = await prisma.employeeAssessment.create({ data: { tenantId: access.tenantId, employeeId, title, type: (text(formData.get('type')) || 'HUMAN') as any, periodType: (text(formData.get('periodType')) || 'MONTHLY') as any, periodLabel: text(formData.get('periodLabel')) || null, reviewerUserId: session?.userId, createdById: session?.userId, jobProfileSnapshot: { capturedAt: new Date().toISOString() }, positionSnapshot: { capturedAt: new Date().toISOString() }, criteria: { create: criteria.map((c) => ({ title: c.title, description: c.description || null, source: 'MANUAL', weight: Math.max(1, Number(c.weight) || 1), snapshot: { title: c.title, weight: c.weight ?? 1 }, score: c.score == null ? undefined : { create: { score: Number(c.score), evidence: c.evidence || 'ثبت نشده' } } })) } } });
  await audit(access.tenantId, employeeId, assessment.id, 'CREATE_ASSESSMENT', session?.userId, null, { title });
  revalidatePath(`/employees/${employeeId}/assessment`); return assessment.id;
}
export async function submitEmployeeAssessmentAction(formData: FormData) { const id = text(formData.get('assessmentId')); const row = await prisma.employeeAssessment.findUnique({ where: { id }, select: { employeeId: true, tenantId: true, status: true } }); if (!row) throw new Error('ارزیابی یافت نشد.'); const access = await getEmployeeAssessmentAccess(row.employeeId); if (!access.canCreate || !['DRAFT','IN_PROGRESS'].includes(row.status)) throw new Error('وضعیت ارزیابی قابل ارسال نیست.'); await prisma.employeeAssessment.update({ where: { id }, data: { status: 'WAITING_APPROVAL', updatedById: access.userId } }); await audit(row.tenantId,row.employeeId,id,'SUBMIT_ASSESSMENT',access.userId,{status:row.status},{status:'WAITING_APPROVAL'}); revalidatePath(`/employees/${row.employeeId}/assessment`); }
export async function finalizeEmployeeAssessmentAction(formData: FormData) { const id = text(formData.get('assessmentId')); const row = await prisma.employeeAssessment.findUnique({ where: { id }, include: { criteria: { include: { score: true } } } }); if (!row) throw new Error('ارزیابی یافت نشد.'); const access = await getEmployeeAssessmentAccess(row.employeeId); if (!access.canManageWorkflow || row.status !== 'WAITING_APPROVAL') throw new Error('اجازه نهایی‌سازی وجود ندارد.'); const totalWeight = row.criteria.reduce((s,c)=>s+c.weight,0) || 1; const total = row.criteria.reduce((s,c)=>s+(Number(c.score?.score ?? 0)*c.weight),0)/totalWeight; const level = total >= 80 ? 'عالی' : total >= 60 ? 'خوب' : total >= 40 ? 'نیازمند بهبود' : 'ضعیف'; await prisma.employeeAssessment.update({ where: { id }, data: { status: 'FINALIZED', totalScore: total, performanceLevel: level, finalizedAt: new Date(), updatedById: access.userId } }); await audit(row.tenantId,row.employeeId,id,'FINALIZE_ASSESSMENT',access.userId,{status:row.status},{status:'FINALIZED',total,level}); revalidatePath(`/employees/${row.employeeId}/assessment`); }

export async function createDevelopmentAction(formData: FormData) { const assessmentId=text(formData.get('assessmentId')); const row=await prisma.employeeAssessment.findUnique({where:{id:assessmentId},select:{id:true,tenantId:true,employeeId:true,status:true}}); if(!row) throw new Error('ارزیابی یافت نشد.'); const access=await getEmployeeAssessmentAccess(row.employeeId); if(!access.canCreate || row.status==='FINALIZED') throw new Error('این ارزیابی نهایی شده و قابل تغییر نیست.'); const action=await prisma.employeeAssessmentAction.create({data:{assessmentId,type:(text(formData.get('type'))||'DEVELOPMENT_PLAN') as any,title:text(formData.get('title'))||'اقدام توسعه',description:text(formData.get('description'))||null,dueDate:text(formData.get('dueDate'))?new Date(text(formData.get('dueDate'))):null,createdById:access.userId}}); await audit(row.tenantId,row.employeeId,row.id,'CREATE_DEVELOPMENT_ACTION',access.userId,null,{actionId:action.id}); revalidatePath(`/employees/${row.employeeId}/assessment/${row.id}`); }
