'use client';
import { useEffect, useState } from 'react';
import { Loader2, X } from 'lucide-react';
import type { BrandInfoDto, BrandInfoType } from '@/app/lib/brand-info/types';
const types: BrandInfoType[] = ['TEXT', 'IMAGE', 'VOICE', 'VIDEO'];
const labels: Record<BrandInfoType, string> = { TEXT: 'متن', IMAGE: 'تصویر', FILE: 'فایل', VOICE: 'صوت', VIDEO: 'ویدیو' };
const accept = (t: BrandInfoType) => t === 'IMAGE' ? '.jpg,.jpeg,.png,.webp' : t === 'VOICE' ? '.webm,.mp3,.wav,.m4a,.ogg' : '.mp4,.webm,.mov';
export function BrandInfoEditDialog({ businessId, brandId, sourceId, onClose, onSaved }: { businessId: string; brandId: string; sourceId: string; onClose: () => void; onSaved: () => void }) {
  const [item, setItem] = useState<BrandInfoDto | null>(null), [type, setType] = useState<BrandInfoType>('TEXT'), [title, setTitle] = useState(''), [text, setText] = useState(''), [file, setFile] = useState<File | null>(null), [error, setError] = useState<string | null>(null), [busy, setBusy] = useState(false);
  useEffect(() => { void fetch(`/api/businesses/${businessId}/taavia/brands/${brandId}/brand-info/${sourceId}`).then(async (r) => { const p = await r.json(); if (!r.ok) throw new Error(p.message); setItem(p.item); setType(p.item.type); setTitle(p.item.title ?? ''); setText(p.item.textContent ?? ''); }).catch((e) => setError(e instanceof Error ? e.message : 'بارگذاری منبع انجام نشد.')); }, [businessId, brandId, sourceId]);
  async function save() { if (!item) return; if (!title.trim()) return setError('عنوان منبع الزامی است.'); if (type === 'TEXT' && !text.trim()) return setError('متن معرفی الزامی است.'); if (type !== 'TEXT' && type !== item.type && !file) return setError('برای تغییر نوع منبع، فایل جدید انتخاب کنید.'); setBusy(true); setError(null); try { let r: Response; if (type === 'TEXT') r = await fetch(`/api/businesses/${businessId}/taavia/brands/${brandId}/brand-info/${sourceId}`, { method: 'PATCH', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ expectedRevision: item.revision, type, title, textContent: text }) }); else { const f = new FormData(); f.set('expectedRevision', item.revision); f.set('type', type); f.set('title', title); if (file) f.set('file', file); r = await fetch(`/api/businesses/${businessId}/taavia/brands/${brandId}/brand-info/${sourceId}`, { method: 'PATCH', body: f }); } const p = await r.json(); if (!r.ok) throw new Error(p.message ?? 'ذخیره تغییرات انجام نشد.'); onSaved(); } catch (e) { setError(e instanceof Error ? e.message : 'ذخیره تغییرات انجام نشد.'); } finally { setBusy(false); } }
  return <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/75 p-4" dir="rtl" role="dialog" aria-modal="true" aria-labelledby="brand-edit-title"><div className="max-h-[90vh] w-full max-w-2xl overflow-y-auto rounded-3xl border border-white/10 bg-slate-900 p-5"><div className="flex items-start justify-between"><div><h2 id="brand-edit-title" className="m-0 text-lg font-black text-white">ویرایش معرفی برند</h2><p className="m-0 mt-1 text-sm text-slate-400">اطلاعات منبع را ویرایش کنید.</p></div><button type="button" onClick={onClose} className="grid h-11 w-11 place-items-center rounded-xl text-slate-300" aria-label="بستن"><X className="h-5 w-5" /></button></div>{!item && !error ? <p className="mt-6 text-sm text-slate-300">در حال بارگذاری منبع…</p> : null}{item ? <><div className="mt-5 grid grid-cols-2 gap-2 md:grid-cols-4">{types.map((t) => <button type="button" key={t} onClick={() => setType(t)} aria-pressed={type === t} className={`min-h-16 rounded-xl border text-sm ${type === t ? 'border-purple-300 bg-purple-400/15 text-purple-100' : 'border-white/10 text-slate-300'}`}>{labels[t]}</button>)}</div><div className="mt-5 grid gap-4"><label className="grid gap-2 text-sm text-slate-200" htmlFor="edit-title">عنوان *<input id="edit-title" value={title} onChange={(e) => setTitle(e.target.value)} maxLength={300} className="min-h-11 rounded-xl border border-white/10 bg-white/5 px-3 text-white" /></label>{type === 'TEXT' ? <label className="grid gap-2 text-sm text-slate-200" htmlFor="edit-text">متن معرفی *<textarea id="edit-text" value={text} onChange={(e) => setText(e.target.value)} maxLength={100000} rows={8} className="rounded-xl border border-white/10 bg-white/5 p-3 text-white" /><span className="text-xs text-slate-400">{text.length.toLocaleString('fa-IR')} / ۱۰۰٬۰۰۰</span></label> : <div className="rounded-2xl border border-white/10 bg-white/[0.03] p-4"><p className="m-0 mb-3 text-sm text-slate-300">{item.media ? <>فایل فعلی: <bdi dir="ltr">{item.media.extension.toUpperCase()}</bdi></> : 'فایل فعلی ندارد'}</p><label className="cursor-pointer text-sm text-purple-100">{file ? <bdi dir="ltr">{file.name}</bdi> : 'تغییر فایل'}<input type="file" accept={accept(type)} className="sr-only" onChange={(e) => setFile(e.target.files?.[0] ?? null)} /></label></div>}</div>{error ? <p role="alert" className="rounded-xl bg-red-400/10 p-3 text-sm text-red-100">{error}</p> : null}<div className="mt-4 flex justify-start gap-2"><button type="button" onClick={onClose} disabled={busy} className="min-h-11 rounded-xl border border-white/10 px-4 text-slate-200">انصراف</button><button type="button" onClick={() => void save()} disabled={busy} className="inline-flex min-h-11 items-center gap-2 rounded-xl bg-purple-400 px-4 font-black text-slate-950">{busy ? <Loader2 className="h-4 w-4 animate-spin" /> : null}ذخیره تغییرات</button></div></> : error ? <p role="alert" className="mt-5 text-sm text-red-100">{error}</p> : null}</div></div>;
}
