ALTER TABLE "Unit" ADD COLUMN IF NOT EXISTS "category" TEXT NOT NULL DEFAULT 'unit';
ALTER TABLE "Unit" ADD COLUMN IF NOT EXISTS "unitType" TEXT;
ALTER TABLE "Unit" ADD COLUMN IF NOT EXISTS "usage" TEXT NOT NULL DEFAULT 'residential';
ALTER TABLE "Unit" ADD COLUMN IF NOT EXISTS "saleEnabled" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "Unit" ADD COLUMN IF NOT EXISTS "deliveryStatus" TEXT NOT NULL DEFAULT 'ready';
ALTER TABLE "Unit" ADD COLUMN IF NOT EXISTS "area" DOUBLE PRECISION;
ALTER TABLE "Unit" ADD COLUMN IF NOT EXISTS "balconyCount" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Unit" ADD COLUMN IF NOT EXISTS "bedroomCount" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Unit" ADD COLUMN IF NOT EXISTS "postalCode" TEXT;
ALTER TABLE "Unit" ADD COLUMN IF NOT EXISTS "amenities" JSONB NOT NULL DEFAULT '[]'::jsonb;
ALTER TABLE "Unit" ADD COLUMN IF NOT EXISTS "direction" TEXT NOT NULL DEFAULT 'unknown';
ALTER TABLE "Unit" ADD COLUMN IF NOT EXISTS "assignedToUnitId" TEXT;
ALTER TABLE "Unit" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "Unit" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

CREATE INDEX IF NOT EXISTS "Unit_tenantId_blockId_category_idx" ON "Unit"("tenantId", "blockId", "category");
CREATE INDEX IF NOT EXISTS "Unit_tenantId_assignedToUnitId_idx" ON "Unit"("tenantId", "assignedToUnitId");
