import { notFound } from 'next/navigation';
import { prisma } from '../../../../lib/prisma';
import { getSessionContext } from '../../../../lib/auth';
import { getOffboardingAccess } from '../../../../lib/offboarding-access';
import { getEmployeeAssetClearance } from '../../../../lib/asset-clearance-provider';
import { createEmployeeTerminationIntentAction } from '../../../../lib/actions';
import { handleEmployeeOffboardingAction, rejectOrReturnOffboardingAction, restoreEmployeeAccess } from '../../../../lib/offboarding-workflow-actions';

const types = ['RESIGNATION','COMPANY_TERMINATION','CONTRACT_END','NON_RENEWAL','DISMISSAL','LAYOFF','PROBATION_END','ABANDONMENT','RETIREMENT','DEATH','MUTUAL_AGREEMENT'];
const stepLabels: Record<string,string> = { MANAGER_REVIEW:'بررسی مدیر', HR_REVIEW:'تأیید منابع انسانی', FINANCE_CLEARANCE:'تسویه مالی', IT_CLEARANCE:'قطع دسترسی', FINALIZATION:'نهایی‌سازی' };

export default async function OffboardingPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params; const session = await getSessionContext(); if (!session?.tenantId) notFound();
  const access = await getOffboardingAccess(id); if (!access?.canView) notFound();
  const employee = await prisma.employee.findFirst({ where: { id, tenantId: session.tenantId }, include: { terminationIntents: { orderBy: { createdAt: 'desc' }, take: 1, include: { approvalSteps: { orderBy: { sequence: 'asc' } } } } } });
  if (!employee) notFound(); const process = employee.terminationIntents[0];
  const [contracts, financial, requests, documents, asset] = await Promise.all([
    prisma.employeeContract.count({ where: { tenantId: session.tenantId, employeeId: id, status: { in: ['active','SUBMITTED','PENDING_APPROVAL','APPROVED'] } } }),
    prisma.employeeFinancialItem.count({ where: { tenantId: session.tenantId, employeeId: id, status: { in: ['DRAFT','PENDING_APPROVAL','APPROVED','APPLIED_TO_PAYROLL'] } } }),
    prisma.employeeRequest.count({ where: { tenantId: session.tenantId, employeeId: id, status: { in: ['pending','approved'] } } }),
    prisma.employeeDocument.count({ where: { tenantId: session.tenantId, employeeId: id, status: 'PENDING_APPROVAL' } }),
    getEmployeeAssetClearance({ tenantId: session.tenantId, employeeId: id }),
  ]);
  const action = process ? process.status === 'DRAFT' ? ['SUBMIT','ارسال',access.canSubmit] : process.status === 'SUBMITTED' ? ['APPROVE','تأیید مدیر',access.canManagerApprove] : process.status === 'APPROVAL_PENDING' ? ['APPROVE','تأیید منابع انسانی',access.canHrApprove] : process.status === 'SETTLEMENT' ? ['SETTLE','تکمیل تسویه',access.canFinance] : process.status === 'ACCESS_REVOCATION' ? ['ACCESS_DISABLE','قطع دسترسی',access.canAccess] : process.status === 'READY_FOR_FINALIZATION' ? ['FINALIZE','نهایی‌سازی',access.canFinalize] : process.status === 'COMPLETED' ? ['ARCHIVE','آرشیو',access.canArchive] : null : null;
  return <main className="page-stack" dir="rtl" lang="fa"><header className="module-page-header"><div><p>پرونده کارکنان</p><h1>خاتمه همکاری · {employee.firstName} {employee.lastName}</h1></div></header>
    {!process ? <section className="rounded-2xl border bg-white p-6"><h2 className="text-xl font-bold">شروع فرایند خاتمه همکاری</h2><form action={createEmployeeTerminationIntentAction} className="mt-5 grid gap-4 md:grid-cols-2"><input type="hidden" name="employeeId" value={id}/><label>نوع خاتمه<select name="terminationType" required className="mt-1 block w-full rounded-xl border p-3">{types.map(t=><option key={t}>{t}</option>)}</select></label><label>دلیل<input name="reason" required className="mt-1 block w-full rounded-xl border p-3"/></label><label>تاریخ اعلام<input type="date" name="announcementDate" required className="mt-1 block w-full rounded-xl border p-3"/></label><label>آخرین روز کاری<input type="date" name="proposedLastWorkingDay" required className="mt-1 block w-full rounded-xl border p-3"/></label><label>تاریخ اثرگذاری<input type="date" name="effectiveTerminationDate" required className="mt-1 block w-full rounded-xl border p-3"/></label>{access.canCreate&&<button className="rounded-xl bg-slate-900 p-3 font-bold text-white md:col-span-2">ایجاد فرایند</button>}</form></section> : <>
      <section className="rounded-2xl border bg-white p-6"><div className="flex flex-wrap justify-between gap-3"><div><p className="text-sm text-slate-500">وضعیت فعلی</p><h2 className="text-2xl font-bold">{process.status}</h2></div><span className="rounded-full bg-slate-100 px-4 py-2">مرحله بعد: {process.nextAction}</span></div><div className="mt-5 grid gap-3 md:grid-cols-4 text-sm"><div>نوع خروج<br/><b>{process.terminationType}</b></div><div>مسئول مرحله<br/><b>{process.stageOwner}</b></div><div>تسویه<br/><b>{process.settlementStatus}</b></div><div>دسترسی<br/><b>{process.accessStatus}</b></div></div></section>
      <section className="rounded-2xl border bg-white p-6"><h2 className="font-bold">Workflow Timeline</h2><div className="mt-4 grid gap-3 md:grid-cols-5">{process.approvalSteps.map(step=><article key={step.id} className="rounded-xl border p-3"><b>{stepLabels[step.stepType]??step.stepType}</b><p className="mt-2 text-sm">{step.status}</p><small className="text-slate-500">تأییدکننده: {step.approverId??'تخصیص در زمان اقدام'}</small></article>)}</div></section>
      <section className="rounded-2xl border bg-white p-6"><h2 className="font-bold">Clearance Summary</h2><div className="mt-4 grid gap-3 md:grid-cols-5 text-sm"><div>قرارداد باز<br/><b>{contracts}</b></div><div>مالی و وام باز<br/><b>{financial}</b></div><div>درخواست باز<br/><b>{requests}</b></div><div>سند Pending<br/><b>{documents}</b></div><div>دارایی<br/><b>{asset.status}</b><small className="block text-slate-500">{asset.reason}</small></div></div></section>
      <section className="rounded-2xl border bg-white p-6"><h2 className="font-bold">عملیات مجاز</h2><div className="mt-4 flex flex-wrap gap-3">{action&&action[2]&&<form action={handleEmployeeOffboardingAction}><input type="hidden" name="id" value={process.id}/><input type="hidden" name="action" value={String(action[0])}/><input name="comment" placeholder="توضیح اختیاری" className="rounded-xl border p-3"/><button className="rounded-xl bg-slate-900 px-4 py-3 text-white">{String(action[1])}</button></form>}{['SUBMITTED','APPROVAL_PENDING'].includes(process.status)&&<>{(process.status==='SUBMITTED'?access.canManagerApprove:access.canHrApprove)&&['RETURNED','REJECTED'].map(decision=><form key={decision} action={rejectOrReturnOffboardingAction}><input type="hidden" name="id" value={process.id}/><input type="hidden" name="decision" value={decision}/><input name="reason" required placeholder="دلیل الزامی" className="rounded-xl border p-3"/><button className="rounded-xl border px-4 py-3">{decision==='RETURNED'?'بازگشت':'رد'}</button></form>)}</>}{process.accessStatus==='DISABLED'&&access.canRestore&&<form action={restoreEmployeeAccess}><input type="hidden" name="id" value={process.id}/><input name="reason" required placeholder="دلیل بازیابی" className="rounded-xl border p-3"/><button className="rounded-xl border px-4 py-3">بازیابی دسترسی</button></form>}</div></section>
    </>}</main>;
}
