'use client';

import Link from 'next/link';
import { ArrowLeft, Eye, Info } from 'lucide-react';
import { TaavBadge, TaavButton, TaavCard } from '@repo/ui/taav/primitives';
import { TaavTableActions, TaavTableBody, TaavTableCell, TaavTableHead, TaavTableHeader, TaavTableRow, TaavTableShell } from '@repo/ui/taav/data-display';
import type { TaaviaKnowledgeBaseVersionsOverview } from '@/app/lib/types/taavia-knowledge-base-versions';

type Props = { businessId: string; brandId: string; brandName: string; brandStatus: 'ACTIVE' | 'INACTIVE' | 'ARCHIVED'; brandIcon: string | null; initialData: TaaviaKnowledgeBaseVersionsOverview };

export function TaaviaKnowledgeBaseVersionsClient({ businessId, brandId, brandName, brandStatus, brandIcon, initialData }: Props) {
  const base = `/businesses/${businessId}/products/taavia/brands/${brandId}`;
  const initials = brandName.slice(0, 2) || 'TA';
  return <main dir="rtl" className="mx-auto grid max-w-7xl gap-3 pb-6">
    <header className="grid gap-3 rounded-[var(--taav-radius-xl)] border border-[var(--taav-border-subtle)] bg-[var(--taav-surface)] p-3 shadow-[var(--taav-shadow-sm)]"><div className="flex flex-wrap items-start justify-between gap-3"><div className="flex items-center gap-2.5 text-right"><div className="flex h-11 w-11 items-center justify-center overflow-hidden rounded-[var(--taav-radius-lg)] bg-[var(--taav-brand-soft)] text-sm font-black text-[var(--taav-brand-strong)]">{brandIcon ? <img src={brandIcon} alt="" className="h-full w-full object-cover" /> : initials}</div><div><h1 className="m-0 text-base font-black text-[var(--taav-text-strong)]">نسخه‌های دانشنامه {brandName}</h1><p className="mt-1 text-xs text-[var(--taav-text-muted)]">یک نسخه را برای مشاهدهٔ جزئیات انتخاب کنید.</p></div></div><Link href={base}><TaavButton size="sm" variant="secondary" iconStart={<ArrowLeft className="h-4 w-4" />}>بازگشت به برند</TaavButton></Link></div><div className="flex justify-end"><TaavBadge tone={brandStatus === 'ACTIVE' ? 'success' : 'neutral'} variant="soft" size="sm">برند {brandStatus === 'ACTIVE' ? 'فعال' : 'غیرفعال'}</TaavBadge></div></header>
    <section className="flex items-start gap-3 rounded-xl border border-[var(--taav-brand)]/40 bg-[var(--taav-brand-soft)]/40 p-4 text-right"><Info className="mt-0.5 h-5 w-5 shrink-0 text-[var(--taav-brand-strong)]" /><p className="m-0 text-sm leading-7 text-[var(--taav-text-body)]">نسخه‌های فعال و تاریخی با یک صفحهٔ جزئیات مشترک نمایش داده می‌شوند؛ نسخه‌های غیرفعال فقط‌خواندنی هستند.</p></section>
    <TaavCard variant="outlined" padding="md" radius="xl"><div className="overflow-x-auto"><TaavTableShell variant="bordered" density="compact"><TaavTableHeader><TaavTableRow><TaavTableHead>وضعیت</TaavTableHead><TaavTableHead>نسخه</TaavTableHead><TaavTableHead>نوع ساخت</TaavTableHead><TaavTableHead>تاریخ ساخت</TaavTableHead><TaavTableHead>دسته‌بندی‌ها</TaavTableHead><TaavTableHead>Snapshotها</TaavTableHead><TaavTableHead>توضیحات</TaavTableHead><TaavTableActions>عملیات</TaavTableActions></TaavTableRow></TaavTableHeader><TaavTableBody>{initialData.versions.map((item) => <TaavTableRow key={item.knowledgeBaseId} className={item.isActive ? 'bg-[var(--taav-brand-soft)]/40' : ''}><TaavTableCell><TaavBadge tone={item.isActive ? 'success' : 'neutral'} variant="soft">{item.isActive ? 'فعال' : 'غیرفعال'}</TaavBadge></TaavTableCell><TaavTableCell><bdi dir="ltr">{item.versionLabel}</bdi></TaavTableCell><TaavTableCell>{item.buildType}</TaavTableCell><TaavTableCell>{item.createdAt}</TaavTableCell><TaavTableCell>{item.categoryCount}</TaavTableCell><TaavTableCell>{item.sourceSnapshotCount}</TaavTableCell><TaavTableCell>{item.description}</TaavTableCell><TaavTableActions><Link href={`${base}/knowledge-base/${item.knowledgeBaseId}`}><TaavButton size="sm" variant="secondary" iconStart={<Eye className="h-4 w-4" />}>مشاهده جزئیات</TaavButton></Link></TaavTableActions></TaavTableRow>)}</TaavTableBody></TaavTableShell></div></TaavCard>
  </main>;
}
