'use client';

import Link from 'next/link';
import { useMemo, useState } from 'react';
import { ArrowLeft, BookOpen, ChevronLeft, Eye, FileText, Folder, GitBranch, ListTree, Search, Shapes } from 'lucide-react';
import { TaavBadge, TaavButton, TaavCard } from '@repo/ui/taav/primitives';
import { TaavEmptyState } from '@repo/ui/taav/data-display';
import { TaavTabs, TaavTabsList, TaavTabsTrigger } from '@repo/ui/taav/navigation';
import type { KnowledgeBaseCategoriesPageData, KnowledgeBaseCategoryDetail } from '@/app/lib/types/taavia-knowledge-base-categories';

type Props = { businessId: string; brandId: string; brandName: string; brandStatus: 'ACTIVE' | 'INACTIVE' | 'ARCHIVED'; brandIcon: string | null; initialData: KnowledgeBaseCategoriesPageData };

const sourceTone = { DOCX: 'info', PDF: 'danger', PNG: 'success', URL: 'neutral' } as const;

export function TaaviaKnowledgeBaseCategoriesClient({ businessId, brandId, brandName, brandStatus, brandIcon, initialData }: Props) {
  const [selectedCategoryId, setSelectedCategoryId] = useState(initialData.categories.find((category) => category.level === 1)?.categoryId ?? '');
  const [query, setQuery] = useState('');
  const [feedback, setFeedback] = useState<string | null>(null);
  const brandsHref = `/businesses/${businessId}/products/taavia/brands`;
  const overviewHref = `/businesses/${businessId}/products/taavia/brands/${brandId}/knowledge-base`;
  const sourcesHref = `${overviewHref}/sources`;
  const categoriesHref = `${overviewHref}/categories`;
  const initials = brandName.trim().slice(0, 2) || 'TA';
  const brandStatusLabel = brandStatus === 'ACTIVE' ? 'فعال' : brandStatus === 'INACTIVE' ? 'غیرفعال' : 'آرشیوشده';
  const selected = initialData.categories.find((category) => category.categoryId === selectedCategoryId) ?? initialData.categories[0];
  const visibleCategoryIds = useMemo(() => new Set(initialData.categories.filter((category) => category.title.includes(query.trim()) || initialData.categories.some((parent) => parent.categoryId === category.parentCategoryId && parent.title.includes(query.trim()))).map((category) => category.categoryId)), [initialData.categories, query]);
  const rootCategories = initialData.categories.filter((category) => category.level === 1 && (visibleCategoryIds.has(category.categoryId) || initialData.categories.some((child) => child.parentCategoryId === category.categoryId && visibleCategoryIds.has(child.categoryId))));
  const totalLevelOne = initialData.categories.filter((category) => category.level === 1).length;

  const renderCategory = (category: KnowledgeBaseCategoryDetail) => {
    const isSelected = category.categoryId === selected.categoryId;
    const children = initialData.categories.filter((item) => item.parentCategoryId === category.categoryId && visibleCategoryIds.has(item.categoryId));
    return <div key={category.categoryId} className="grid gap-1"><button type="button" onClick={() => setSelectedCategoryId(category.categoryId)} className={`flex min-h-10 items-center justify-between gap-2 rounded-[var(--taav-radius-md)] px-2.5 text-right text-sm font-bold transition focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--taav-brand)] ${isSelected ? 'bg-[var(--taav-brand-soft)] text-[var(--taav-brand-strong)]' : 'text-[var(--taav-text-body)] hover:bg-[var(--taav-surface-soft)]'}`}><span className="flex min-w-0 items-center gap-2"><Folder className="h-4 w-4 shrink-0" />{category.title}</span>{category.childCount > 0 ? <span className="rounded-full bg-black/10 px-1.5 py-0.5 text-[10px]">{category.childCount}</span> : null}</button>{children.map((child) => <button key={child.categoryId} type="button" onClick={() => setSelectedCategoryId(child.categoryId)} className={`mr-4 flex min-h-9 items-center justify-between gap-2 rounded-[var(--taav-radius-md)] border-r border-[var(--taav-border-subtle)] pr-3 text-right text-xs transition focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--taav-brand)] ${child.categoryId === selected.categoryId ? 'text-[var(--taav-brand-strong)]' : 'text-[var(--taav-text-muted)] hover:text-[var(--taav-text-strong)]'}`}><span>{child.title}</span><span className="text-[10px]">سطح ۲</span></button>)}</div>;
  };

  return <main dir="rtl" className="mx-auto grid max-w-7xl gap-4 pb-10">
    <header className="grid gap-4 rounded-[var(--taav-radius-xl)] border border-[var(--taav-border-subtle)] bg-[var(--taav-surface)] p-4 shadow-[var(--taav-shadow-sm)] md:p-5"><div className="relative min-h-16"><div className="absolute right-0 top-0 flex min-w-0 items-center gap-3 text-right"><div className="flex h-16 w-16 shrink-0 items-center justify-center overflow-hidden rounded-[var(--taav-radius-xl)] border border-[var(--taav-border-subtle)] bg-[var(--taav-brand-soft)] text-xl font-black text-[var(--taav-brand-strong)]">{brandIcon ? <img src={brandIcon} alt="" className="h-full w-full object-cover" /> : initials}</div><div><h1 className="m-0 text-[clamp(1.15rem,2vw,1.55rem)] font-black text-[var(--taav-text-strong)]">مدیریت دانش برند {brandName}</h1><p className="mt-1.5 text-[length:var(--taav-text-sm)] text-[var(--taav-text-muted)]">مرکز مدیریت Knowledge Base این برند</p></div></div><Link href={brandsHref} className="absolute left-0 top-1"><TaavButton variant="secondary" size="sm" iconStart={<ArrowLeft className="h-4 w-4" />}>بازگشت به برندها</TaavButton></Link></div><div className="flex flex-wrap items-center justify-between gap-3 border-t border-[var(--taav-border-subtle)] pt-3"><TaavTabs value="categories" dir="rtl"><TaavTabsList className="flex flex-wrap justify-end gap-1 bg-transparent p-0"><TaavTabsTrigger value="overview" asChild><Link href={overviewHref}>نمای کلی</Link></TaavTabsTrigger><TaavTabsTrigger value="sources" asChild><Link href={sourcesHref}>منابع</Link></TaavTabsTrigger><TaavTabsTrigger value="categories" asChild><Link href={categoriesHref}>دسته‌بندی‌ها</Link></TaavTabsTrigger><TaavTabsTrigger value="builds" disabled>ساخت‌ها</TaavTabsTrigger><TaavTabsTrigger value="versions" disabled>نسخه‌ها</TaavTabsTrigger></TaavTabsList></TaavTabs><TaavBadge tone={brandStatus === 'ACTIVE' ? 'success' : 'neutral'} variant="soft">برند {brandStatusLabel}</TaavBadge></div><nav aria-label="مسیر دسته‌بندی‌های دانشنامه" className="flex flex-wrap items-center justify-end gap-2 text-[11px] text-[var(--taav-text-muted)]"><Link href={brandsHref}>مدیریت برندها</Link><span>←</span><span className="font-bold text-[var(--taav-text-body)]">{brandName}</span><span>←</span><Link href={overviewHref}>مدیریت دانش</Link><span>←</span><span>دسته‌بندی‌ها</span></nav></header>
    {feedback ? <div role="status" className="rounded-[var(--taav-radius-lg)] border border-[var(--taav-info)]/30 bg-[var(--taav-info)]/10 px-4 py-3 text-right text-sm text-[var(--taav-text-strong)]">{feedback}</div> : null}
    <TaavCard variant="outlined" padding="md" radius="xl"><div className="flex flex-wrap items-center justify-between gap-3"><div className="flex flex-wrap items-center gap-4 text-right text-sm"><TaavBadge tone="success" variant="soft">فعال</TaavBadge><span className="text-[var(--taav-text-muted)]">{initialData.activeVersionLabel}</span><span className="text-[var(--taav-text-muted)]">آخرین به‌روزرسانی: <span dir="ltr">{initialData.updatedAt}</span></span></div><TaavButton size="sm" variant="secondary" iconStart={<Eye className="h-4 w-4" />} onClick={() => setFeedback('مشاهده نسخه فعال در مرحله بعدی پیاده‌سازی می‌شود.')}>مشاهده نسخه فعال</TaavButton></div></TaavCard>
    <section dir="ltr" className="grid gap-4 xl:grid-cols-[260px_minmax(0,1fr)_330px]"><div dir="rtl"><TaavCard variant="outlined" padding="md" radius="xl"><div className="mb-3 flex items-center gap-2 text-right"><ListTree className="h-5 w-5 text-[var(--taav-brand-strong)]" /><h2 className="m-0 font-black text-[var(--taav-text-strong)]">دسته‌بندی‌ها</h2></div><label className="relative block"><Search className="pointer-events-none absolute right-3 top-3 h-4 w-4 text-[var(--taav-text-muted)]" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="جستجو در دسته‌بندی‌ها..." className="min-h-10 w-full rounded-[var(--taav-radius-md)] border border-[var(--taav-border-subtle)] bg-[var(--taav-surface-soft)] pr-9 pl-3 text-right text-sm text-[var(--taav-text-strong)] outline-none focus:ring-2 focus:ring-[var(--taav-brand)]" /></label><div className="mt-3 max-h-[420px] space-y-1 overflow-y-auto">{rootCategories.length ? rootCategories.map(renderCategory) : <TaavEmptyState variant="search" size="sm" title="دسته‌ای یافت نشد" />}</div><div className="mt-4 flex items-center justify-between border-t border-[var(--taav-border-subtle)] pt-3 text-xs"><span className="text-[var(--taav-text-muted)]">جمع کل دسته‌بندی‌ها</span><strong className="text-[var(--taav-text-strong)]">{totalLevelOne}</strong></div><Link href={overviewHref} className="mt-3 inline-flex"><TaavButton size="sm" variant="secondary" iconStart={<ArrowLeft className="h-4 w-4" />}>بازگشت به دانشنامه</TaavButton></Link></TaavCard></div>
      <div dir="rtl"><TaavCard variant="outlined" padding="md" radius="xl"><div className="flex flex-wrap items-start justify-between gap-3 text-right"><div><h2 className="m-0 text-[length:var(--taav-text-xl)] font-black text-[var(--taav-text-strong)]">{selected.title}</h2><div className="mt-3 flex flex-wrap gap-x-5 gap-y-2 text-xs text-[var(--taav-text-muted)]"><span>سطح {selected.level === 1 ? 'اول' : 'دوم'}</span><span dir="ltr">شناسه: {selected.categoryId}</span><span>زیردسته‌ها: {selected.childCount}</span><span dir="ltr">ایجاد: {selected.createdAt}</span><span dir="ltr">به‌روزرسانی: {selected.updatedAt}</span></div></div><TaavButton size="sm" variant="secondary" iconStart={<GitBranch className="h-4 w-4" />} onClick={() => setFeedback('مشاهده تغییرات در این مرحله فقط یک جای‌نگهدار است.')}>مشاهده تغییرات</TaavButton></div><div className="mt-5 border-t border-[var(--taav-border-subtle)] pt-4"><div className="mb-3 flex items-center gap-2"><BookOpen className="h-5 w-5 text-[var(--taav-brand-strong)]" /><h3 className="m-0 font-black text-[var(--taav-text-strong)]">محتوای این دسته‌بندی</h3></div><article className="max-h-[440px] overflow-y-auto rounded-[var(--taav-radius-lg)] border border-[var(--taav-border-subtle)] bg-[var(--taav-surface-soft)] px-5 py-4 text-right text-sm leading-9 text-[var(--taav-text-body)]">{selected.content.map((paragraph, index) => <p key={index} className={index === 0 ? 'm-0' : 'mt-5'}>{paragraph}</p>)}</article></div></TaavCard></div>
      <div dir="rtl"><TaavCard variant="outlined" padding="md" radius="xl"><div className="mb-4 flex items-center gap-2 text-right"><Shapes className="h-5 w-5 text-[var(--taav-brand-strong)]" /><div><h2 className="m-0 font-black text-[var(--taav-text-strong)]">منابع استفاده‌شده در ساخت این دسته‌بندی</h2><p className="mt-1 text-xs text-[var(--taav-text-muted)]">{selected.sources.length} منبع Snapshot</p></div></div><div className="space-y-2">{selected.sources.map((source) => <div key={source.sourceSnapshotId} className="flex items-center justify-between gap-2 rounded-[var(--taav-radius-lg)] border border-[var(--taav-border-subtle)] bg-[var(--taav-surface-soft)] p-3 text-right"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><strong className="truncate text-sm text-[var(--taav-text-strong)]">{source.title}</strong><TaavBadge tone={sourceTone[source.sourceType]} variant="soft">{source.sourceType}</TaavBadge></div><p className="mt-1 text-[10px] text-[var(--taav-text-muted)]"><span>{source.snapshotLabel}</span> · <span dir="ltr">{source.usedAt}</span></p></div>{source.previewRoute ? <Link href={source.previewRoute} aria-label={`مشاهده ${source.title}`} className="shrink-0 rounded-md p-2 text-[var(--taav-brand-strong)] hover:bg-[var(--taav-brand-soft)] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--taav-brand)]"><Eye className="h-4 w-4" /></Link> : <FileText className="h-4 w-4 shrink-0 text-[var(--taav-text-muted)]" />}</div>)}</div><div className="mt-4 grid"><TaavButton size="sm" variant="secondary" onClick={() => setFeedback('فهرست همه منابع این دسته‌بندی در مرحله بعدی پیاده‌سازی می‌شود.')}>مشاهده همه منابع این دسته</TaavButton></div></TaavCard></div>
    </section>
  </main>;
}
