CREATE TABLE "EmployeeSkill" ("id" TEXT NOT NULL,"tenantId" TEXT NOT NULL,"employeeId" TEXT NOT NULL,"title" TEXT NOT NULL,"category" TEXT NOT NULL,"level" TEXT NOT NULL,"description" TEXT,"isActive" BOOLEAN NOT NULL DEFAULT true,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "EmployeeSkill_pkey" PRIMARY KEY ("id"));
CREATE TABLE "EmployeeInterest" ("id" TEXT NOT NULL,"tenantId" TEXT NOT NULL,"employeeId" TEXT NOT NULL,"category" TEXT NOT NULL,"title" TEXT NOT NULL,"description" TEXT,"isActive" BOOLEAN NOT NULL DEFAULT true,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "EmployeeInterest_pkey" PRIMARY KEY ("id"));
CREATE TABLE "EmployeeWorkPreference" ("id" TEXT NOT NULL,"tenantId" TEXT NOT NULL,"employeeId" TEXT NOT NULL,"values" JSONB NOT NULL DEFAULT '{}',"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "EmployeeWorkPreference_pkey" PRIMARY KEY ("id"));
CREATE TABLE "EmployeeHealthProfile" ("id" TEXT NOT NULL,"tenantId" TEXT NOT NULL,"employeeId" TEXT NOT NULL,"physicalHealthNotes" TEXT,"mobilityLimitations" TEXT,"specialMedicalConsiderations" TEXT,"workplaceAccommodationNeeds" TEXT,"mentalHealthNotes" TEXT,"lastReviewedAt" TIMESTAMP(3),"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "EmployeeHealthProfile_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "EmployeeSkill_tenantId_employeeId_title_category_key" ON "EmployeeSkill"("tenantId","employeeId","title","category");
CREATE UNIQUE INDEX "EmployeeInterest_tenantId_employeeId_title_category_key" ON "EmployeeInterest"("tenantId","employeeId","title","category");
CREATE UNIQUE INDEX "EmployeeWorkPreference_employeeId_key" ON "EmployeeWorkPreference"("employeeId");
CREATE UNIQUE INDEX "EmployeeHealthProfile_employeeId_key" ON "EmployeeHealthProfile"("employeeId");
CREATE INDEX "EmployeeSkill_tenantId_employeeId_isActive_idx" ON "EmployeeSkill"("tenantId","employeeId","isActive");
CREATE INDEX "EmployeeInterest_tenantId_employeeId_isActive_idx" ON "EmployeeInterest"("tenantId","employeeId","isActive");
CREATE INDEX "EmployeeWorkPreference_tenantId_employeeId_idx" ON "EmployeeWorkPreference"("tenantId","employeeId");
CREATE INDEX "EmployeeHealthProfile_tenantId_employeeId_idx" ON "EmployeeHealthProfile"("tenantId","employeeId");
ALTER TABLE "EmployeeSkill" ADD CONSTRAINT "EmployeeSkill_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "Tenant"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "EmployeeSkill" ADD CONSTRAINT "EmployeeSkill_employeeId_fkey" FOREIGN KEY ("employeeId") REFERENCES "Employee"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "EmployeeInterest" ADD CONSTRAINT "EmployeeInterest_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "Tenant"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "EmployeeInterest" ADD CONSTRAINT "EmployeeInterest_employeeId_fkey" FOREIGN KEY ("employeeId") REFERENCES "Employee"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "EmployeeWorkPreference" ADD CONSTRAINT "EmployeeWorkPreference_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "Tenant"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "EmployeeWorkPreference" ADD CONSTRAINT "EmployeeWorkPreference_employeeId_fkey" FOREIGN KEY ("employeeId") REFERENCES "Employee"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "EmployeeHealthProfile" ADD CONSTRAINT "EmployeeHealthProfile_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "Tenant"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "EmployeeHealthProfile" ADD CONSTRAINT "EmployeeHealthProfile_employeeId_fkey" FOREIGN KEY ("employeeId") REFERENCES "Employee"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
