import Link from 'next/link';
import { getEmployeeAssessmentCenter } from '../../../../lib/employee-assessment';
import { createEmployeeAssessmentAction, submitEmployeeAssessmentAction, finalizeEmployeeAssessmentAction } from '../../../../lib/employee-assessment-actions';

export default async function AssessmentCenterPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params; const data = await getEmployeeAssessmentCenter(id);
  if (!data.employee) return <main className="module-page"><h1>مرکز ارزیابی و توسعه</h1><p>دسترسی به این بخش برای شما فعال نیست.</p></main>;
  return <main className="module-page" dir="rtl"><div className="module-page__header"><div><p className="eyebrow">پروفایل کارمند</p><h1>مرکز ارزیابی و توسعه</h1><p>{data.employee.firstName} {data.employee.lastName} · ارزیابی عملکرد و برنامه توسعه</p></div><Link className="button button--ghost" href={`/employees/${id}`}>بازگشت به پروفایل</Link></div>
    <section className="stats-grid">{[['آخرین امتیاز', data.summary?.latest?.totalScore ?? '—'],['سطح عملکرد', data.summary?.latest?.performanceLevel ?? '—'],['ارزیابی‌های نهایی', data.summary?.finalizedCount ?? 0],['اقدام‌های باز', data.summary?.openActions.length ?? 0]].map(([l,v])=><article className="stat-card" key={String(l)}><span>{l}</span><strong>{String(v)}</strong></article>)}</section>
    {data.access.canCreate && <form action={createEmployeeAssessmentAction} className="panel-card"><h2>ارزیابی جدید</h2><input type="hidden" name="employeeId" value={id}/><input type="hidden" name="criteriaJson" value='[{"title":"عملکرد کلی","weight":1}]'/><div className="form-grid"><label>عنوان<input name="title" required placeholder="ارزیابی دوره‌ای"/></label><label>دوره<select name="periodType" defaultValue="MONTHLY"><option value="MONTHLY">ماهانه</option><option value="QUARTERLY">فصلی</option><option value="SEMI_ANNUAL">شش‌ماهه</option><option value="ANNUAL">سالانه</option><option value="EVENT_BASED">موردی</option></select></label></div><button className="button" type="submit">ایجاد پیش‌نویس</button></form>}
    <section className="panel-card"><h2>فهرست ارزیابی‌ها</h2>{data.assessments.length === 0 ? <p>هنوز ارزیابی ثبت نشده است.</p> : <div className="stack-list">{data.assessments.map((a)=><article className="list-row" key={a.id}><div><strong>{a.title}</strong><p>{a.status} · {a.assessmentDate.toLocaleDateString('fa-IR')}</p></div><div className="inline-actions"><Link className="button button--ghost" href={`/employees/${id}/assessment/${a.id}`}>جزئیات</Link>{a.status==='DRAFT' && data.access.canCreate && <form action={submitEmployeeAssessmentAction}><input type="hidden" name="assessmentId" value={a.id}/><button className="button button--ghost">ارسال برای تأیید</button></form>}{a.status==='WAITING_APPROVAL' && data.access.canManageWorkflow && <form action={finalizeEmployeeAssessmentAction}><input type="hidden" name="assessmentId" value={a.id}/><button className="button">نهایی‌سازی</button></form>}</div></article>)}</div>}</section>
  </main>;
}
